### ISSUE TITLE
question about 'repondent name' parsing 

### ISSUE THREAD

**Issue by mcqueen1987** [openlawnz/openlawnz-parsers#37]
IN THE HIGH COURT OF NEW ZEALAND
AUCKLAND REGISTRY
CIV-2014-404-000804
[2014] NZHC 2554

IN THE MATTER
of the estate of PETER RICHARD WONG

BETWEEN

ANDREW JAMES WONG
Applicant

Hearing:
2 October 2014
Counsel:
N Penman-Chambers
Judgment:
2 October 2014

JUDGMENT OF ASHER J

**Comment by mcqueen1987** [comment]
BETWEEN
JAMES GORDON NEWLANDS
Plaintiff
AND
SOVEREIGN ASSURANCE COMPANY LIMITED
First Defendant
AND
BRUCE GRAHAM CORTESI
Second Defendant
AND
PLANWISE FINANCIAL SERVICES LIMITED
Third Defendant

On the papers:
3 October 2014
Appearances:
G Keene and P Kemps for the Plaintiff
R Hern for the Second and Third Defendants
Judgment:
3 October 2014

**Comment by mcqueen1987** [comment]
IN THE HIGH COURT OF NEW ZEALAND
AUCKLAND REGISTRY
CIV-2014-404-002066
[2014] NZHC 2405


UNDER
Sections 248(1)(d) and 284(1) of the Companies Act 1993
IN THE MATTER
of an originating application for orders by Kerryn Mark Downey and William Guy Black as liquidators of FAI (NZ) GENERAL INSURANCE COMPANY
LIMITED (IN LIQUIDATION)
Applicants




Hearing:
On the papers
Counsel:
JC Caird and GK Holm-Hansen for applicants
Judgment:
2 October 2014

**Comment by strum3nt** [comment]
## Example 1
No respondent. It is fine for respondent to be null.

## Example 2
Similar to applicant / appellant / plaintiff - there can be many respondents / defendants as per #13. This one has three groups of defendants. Text after "AND" but before "First Defendant" is one defendant name "SOVEREIGN ASSURANCE COMPANY LIMITED". Then after "AND" and before "Second defendant" is second defendant name "BRUCE GRAHAM CORTESI".

The order is not necessary to store - you do not need to store "First", "Second", etc separately unless that is easier. All can be grouped together as "Defendant" in this case and similar cases. 

If you have done separate lists in applicant parser (eg First Appellant = XXX, Second Appellant = YYY) then you could group here if that is easy to do, but if you have not done grouping in applicant parser, it is **not** necessary to add here. I would suggest ALL first / second / third are ignored and grouped together Appellant, Applicant, Respondent, Defendant etc. 

## Example 3 
Respondent = null
