### ISSUE TITLE
Questions about 'In Person' parsing

### ISSUE THREAD

**Issue by mcqueen1987** [openlawnz/openlawnz-parsers#38]
**cast_text:** 
Hearing:
8 October 2014
Appearances:
H Fulton for Plantiffs
A Choi & L M Nicholson for Defendants
Judgment:
14 October 2014

**Question:**
in this case, the 'in person' of Plantiffs is 'H Fulton', and the 'in person' of Defendants is 'A Choi & L M Nicholson'. should we save both of them or just the 'in person' of Plantiffs?
if we save both of them, we need to add new field, or we can save it as a whole string:

_H Fulton for Plantiffs \n A Choi & L M Nicholson for Defendants_

**Comment by mcqueen1987** [comment]
here are 14 cases including failed cases and some typical succeed cases.
could you please review the cases and comments if anything wrong or need improved, thanks

https://docs.google.com/spreadsheets/d/1YPpHRGGUmFbbU5vQA1CpmjY_VzCAwGhn1yw9bziVvZo/edit#gid=1914335140

**Comment by strum3nt** [comment]
There are two options- in other words this data is useful for two different levels. One option is just to find the cases where applicant has no representation or appears "in person". That means they have no lawyer. The other option is to find WHO the lawyer is, including if they no lawyer, for each party in the case.


Our preference, if possible and not too difficult would be to associate with party (second option). You already have party being extracted (appellant / respondent etc), so best if you could associate the party type with one of three options:

1. Name of lawyer
2. In person / self represented
3. Unknown / impossible to parse

However if that will take more than extra week, then I think do not do that. Only look for "in person / self represented" for first party. That will give Tom and co the most important data and we can build the second option later

Can you let me know if you think it will be a lot more work? Then depending on which option we choose, I will edit the spreadsheet so you can see the intended output

**Comment by mcqueen1987** [comment]
I will have a try. the parse is based on regex, therefore it's hard to estimate the cost. I will update this issue later
