### ISSUE TITLE
Question about the relationship between 'ACC text file' and 'cases'

### ISSUE THREAD

**Issue by mcqueen1987** [openlawnz/openlawnz-parsers#39]
Background: 
I am tring to parse 'ACC representative name (ACC only)' and this ACC-only field is parsed from text files listed in this link:
[https://openlawnz-my.sharepoint.com/personal/andrew_openlaw_nz/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fandrew%5Fopenlaw%5Fnz%2FDocuments%2Facc%20text%20files%2Fconverted%20text%20files&originalPath=aHR0cHM6Ly9vcGVubGF3bnotbXkuc2hhcmVwb2ludC5jb20vOmY6L2cvcGVyc29uYWwvYW5kcmV3X29wZW5sYXdfbnovRXRpOGhrVl9HSTVLalBzVlpmcDV3QmdCX2Y5aS1lNENLMEpoMEs1MVJ4cUJXQT9ydGltZT03d3gxVWF1OTEwZw](url)
What I gonna do is:
1, match each file in the link above to our database. for example, the file 
039-2004.txt  --> cases.cases:case_id
2, writing a parse file to parse 'ACC representative name' from this txt file.
3, save the parsed  'ACC representative name' with cases.cases:case_id, e.x:
case_id  ACC_epresentative_name
12544                Jone

Question: 
I can not find the corresponding case_id of the txt file. e.x:
039-2004.txt  --> case_id = 20323;
so how to get their relationship?

**Comment by mcqueen1987** [comment]
Question 2:

1, there are 154 ACC cases in table cases.cases in our database and 120 txt ACC files in  this link:
[https://openlawnz-my.sharepoint.com/personal/andrew_openlaw_nz/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fandrew%5Fopenlaw%5Fnz%2FDocuments%2Facc%20text%20files%2Fconverted%20text%20files&originalPath=aHR0cHM6Ly9vcGVubGF3bnotbXkuc2hhcmVwb2ludC5jb20vOmY6L2cvcGVyc29uYWwvYW5kcmV3X29wZW5sYXdfbnovRXRpOGhrVl9HSTVLalBzVlpmcDV3QmdCX2Y5aS1lNENLMEpoMEs1MVJ4cUJXQT9ydGltZT03d3gxVWF1OTEwZw](url)
does all the files in the link included in the cases.cases table? 

2, if it already included in cases table, we don't need to parse  'ACC representative name' from txt files seperately, coz it has already parsed in the file parseCases.js and saved to:
                'appellant_appearance',
                'respondent_appearance',
in cases.cases table.

3, if it doesn't included in cases table, according to the 154 ACC cases in the cases table, should we only parse those files and ignore the 120 txt ACC files? coz form my point of view, the sample is big enouth for parsing a fild. what's your opinion?

**Comment by strum3nt** [comment]
Ahh I see.

The ACC data is **not** in the database yet. We only have 154 there for testing. There will be about 8,000 total files to be added once @williamparry has connected the data-aggregator repository.

Therefore with the example case files you have in the link above with 120 cases, most will not be in the database at all. Those are just random ones I put in the folder for you.

If you have respondent_appearance working, and it works on the 154 cases in the cases table, then you are correct: "ACC representative name" is unnecessary. Can just use "respondent_appearance".

**Comment by strum3nt** [comment]
Ahh I see.

The ACC data is **not** in the database yet. We only have 154 there for now as we imported a small selection into live to start with, and haven't added the rest. There will be about 8,000 total files to be added once @williamparry has connected the data-aggregator repository.

Therefore with the example case files you have in the link above with 120 cases, most will not be in the database at all. Those are just random ones I put in the folder for you.

If you have respondent_appearance working, and it works on the 154 cases already in the cases table, then you are correct: "ACC representative name" is unnecessary. Can just use "respondent_appearance". Therefore "ACC representative name" does not need to be built as a separate parser.
